name = "abu-dhabi-guide-api"
main = "workers/api.js"
compatibility_date = "2024-01-01"

[env.production]
name = "abu-dhabi-guide-api"
routes = [
  { pattern = "abudhabi.alonglfb.com/api/*", zone_name = "alonglfb.com" }
]

[env.staging]
name = "abu-dhabi-guide-api-staging"

# KV Storage for user data
[[kv_namespaces]]
binding = "USER_DATA"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

# D1 Database for structured data
[[d1_databases]]
binding = "DB"
database_name = "abu-dhabi-guide"
database_id = "your_d1_database_id"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Secrets (set via wrangler secret put)
# WEATHER_API_KEY
# EXCHANGE_API_KEY
# EMAIL_API_KEY
